version: "3.9"

services:
  electro:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - vault/.env
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: db-sqlserver
    environment:
      - MSSQL_SA_PASSWORD=November@2023
      - ACCEPT_EULA=Y
      - MSSQL_DATA_DIR=/var/opt/sqlserver/data
      - MSSQL_LOG_DIR=/var/opt/sqlserver/log
      - MSSQL_BACKUP_DIR=/var/opt/sqlserver/backup
    ports:
      - '1430:1433'
    volumes:
      - sql-server-data:/var/opt/mssql/
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
      - sqldata:/var/opt/sqlserver/data/
  sqlserver1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password01
      - MSSQL_PID=Developer
    ports:
      - "1431:1433"

  sqlserver2:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password02
      - MSSQL_PID=Developer
    ports:
      - "1432:1433"


volumes:
  sql-server-data:
    driver: local
  sqldata:
  sqllog:
  sqlbackup: